---
- hosts: all
  become: true
  pre_tasks:

  - name: Dpkg fixing in ubuntu servers
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Updating Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- name: Setting up CA on Control Node
  hosts: ubuntu
  become: yes
  vars:
    ca_cert_path: "/etc/ssl/certs/ca.crt"
    ca_key_path: "/etc/ssl/private/ca.key"
    openssl_config_file: "/etc/ssl/openssl.cnf"
    ca_days: 3650
  tasks:
    - name: Installation of OpenSSL
      package:
        name: openssl
        state: latest
       
    - name: Generating CA Private Key
      openssl_privatekey:
        path: "{{ ca_key_path }}"
        size: 4096
      register: ca_key

    - name: Generating CA Certificate
      openssl_csr:
        path: /etc/ssl/certs/ca.csr
        privatekey_path: "{{ ca_key_path }}"
        common_name: "Certificate Authority"
        country_name: "PH"
        state_or_province_name: "Quezon City"
        locality_name: "TIP"
        organization_name: "Computer Engineering"
        email_address: "qd-zamora@tip.edu.ph"
      register: ca_csr

    - name: Self Signed CA Certificate
      openssl_certificate:
        path: "{{ ca_cert_path }}"
        privatekey_path: "{{ ca_key_path }}"
        csr_path: /etc/ssl/certs/ca.csr
        provider: selfsigned
        force: true

  handlers:
    - name: Restart OpenSSL Service
      service:
        name: openssl
        state: restarted
